algoritmo "exercicio44"
var
   vi, vf, inc: inteiro
inicio

      escreval("Digite o primeiro valor: ")
      leia(vi)
      escreval("Digite o último valor: ")
      leia(vf)
      escreval("Digite o incremento: ")
      leia(inc)
      escreval(" ")
      escreva(vi)
      enquanto (vi < vf) faca
               vi <- vi + inc
               escreva(vi, " ")
      fimenquanto
               
fimalgoritmo